config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  get "about", to: "pages#about"
  resources :articles
  resources :users
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: { minimum: 6, maximum: 100}
    validates :description, presence: true, length: { minimum: 10 }
    validates :short_description, presence: true, length: { minimum: 10 , maximum: 300 }
    validates :tag, presence: true

  end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  before_save { self.username = username.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z]+\.[a-z]+\z/i
  validates :email, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end

  def logged_in?
    !!current_user
  end

  def require_user 
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_admin, except: [:index, :show]

    def show
    end

    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(params.require(:article).permit(:title, :description, :short_description, :tag))
        if @article.save
            flash[:notice] = "Blog was created successfully"
            redirect_to @article
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @article.update(params.require(:article).permit(:title, :description, :short_description, :tag))
            flash[:notice] = "Blog was updated successfully"
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path, status: :see_other
    end

    private
    def set_article
        @article = Article.find(params[:id])
    end

    def require_admin
      if !(logged_in? && current_user.admin?)
        flash[:alert] = "Only admins can perform that action"
        redirect_to articles_path
      end
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :set_article, only: [:show]

    def home
      @articles = Article.all
    end

    def about
    end

    private
    def set_article
        @article = Article.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "Your username or password is incorrect"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 6)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Account was updated successfully"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy if !@user.admin?
    if !current_user.admin?
      session[:user_id] = nil
    end
    flash[:notice] = "Account and all associated articles have been successfully deleted"
    redirect_to root_path, status: :see_other
  end
  
  private # private should always be toward the bottom of your code
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own profile"
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  require 'net/http'

  def gravatar?(email)
    gravatar_check = "http://gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}.png?d=404"
    uri = URI.parse(gravatar_check)
    http = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Get.new(uri.request_uri)
    response = http.request(request)
    response.code.to_i != 404 # from d=404 parameter
  end

  def gravatar_for(user, options = { size: 100 })
    email_address = user.email.downcase
    size = options[:size]
    if email_address.to_s == "eabuhajleh@outlook.com"
      image_tag("cover.jpg", alt: user.username, class: "rounded-circle shadow mx-auto d-block", style: "width: #{size}px; height: #{size}px")
    elsif !gravatar?(email_address)
      image_tag("user.png", alt: user.username, class: "rounded-circle shadow mx-auto d-block p-2", style: "width: #{size}px; height: #{size}px")
    else
      hash = Digest::MD5.hexdigest(email_address)
      gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
      image_tag(gravatar_url, alt: user.username, class: "rounded-circle shadow mx-auto d-block")
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="mx-4">
  <%= form_with(model: @article, data: { turbo: false }, local: true) do |f| %>
    <div class="container bg-secondary p-3 rounded shadow">
      <div class="my-3 row">
        <%= f.label :title, class: "col-sm-1 col-form-label text-light", for:"FormControlInput1" %>
        <div class="col-sm-11">
          <%= f.text_field :title, type: "text", class: "form-control shadow", id: "FormControlInput1", placeholder: "Title of Article" %>
        </div>
      </div>
      <div class="my-3 row">
        <%= f.label :short_description, class: "col-sm-1 col-form-label text-light", for: "FormControlTextarea1" %>
        <div class="col-sm-11">
          <%= f.text_area :short_description, class: "form-control shadow", id: "FormControlTextarea1", placeholder: "Brief Description", rows: "1" %>
        </div>
      <div class="my-3 row">
        <%= f.label :description, class: "col-sm-1 col-form-label text-light", for: "FormControlTextarea1" %>
        <div class="col-sm-11">
          <%= f.text_area :description, class: "form-control shadow", id: "FormControlTextarea1", placeholder: "Description", rows: "20" %>
        </div>
      </div>
      <div class="my-3 row">
        <%= f.label :tag, class: "col-sm-1 col-form-label text-light", for: "FormControlTextarea1" %>
        <div class="col-sm-11">
          <%= f.select :tag, options_for_select(['Books', 'Travel', 'Food']), {}, class: "form-control shadow" %>
        </div>
      </div>
      <div class="form-group mb-3 row">
        <%= f.submit class:"btn btn-large btn-outline-dark text-light shadow col-6 fs-4 offset-3 text-wrap", id: "submit-button" %>
      </div>
    </div>
  <% end %>
  <div class="text-center my-3">
    <%= link_to '[ Cancel and return to Blog Posts ]', articles_path, class: "text-decoration-none text-info", id: "return-to-listings" %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center my-4 lead fs-1">Edit Blog Post</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="row justify-content-center mx-5 mb-3">
  <% @articles.reverse.each do |article| %>
    <div class="card blog-snip my-5 bg-transparent border-0">
      <div class="row g-0">
        <div class="col-sm-5 col-lg-4 col-xl-3">
        
        <% if article.id.odd? %>
          <img src="https://images.unsplash.com/photo-1471440671318-55bdbb772f93?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2080&q=80" class="img-fluid blog-photo rounded rounded-5" alt=<%= article.title %>>
        <% else %>
          <img src="https://images.unsplash.com/photo-1574629174070-63e3564b1916?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=849&q=80" class="img-fluid blog-photo rounded rounded-5" alt=<%= article.title %>>
        <% end %>
        </div>
        <div class="offset-sm-1 col-sm-6 col-lg-7 col-xl-8">
          <div class="card-body">
            <small><%= article.tag %></small>
            <h1 class="card-title"><%= link_to article.title, article_path(article), class: "blog-title link-animation-1 text-decoration-none" %></h1>
            <p class="card-text lead"><%= article.short_description %></p>
            <%= link_to 'Read More', article_path(article), class: "read-more" %>
          </div>
          <div class="card-footer border-0 bg-transparent text-muted">
            <small>Created: <%= time_ago_in_words(article.created_at) %> ago &ensp;|&ensp; Edited: <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center my-4 lead fs-1">Create a New Blog Post</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center blog-title mt-4 fw-bold"><%= @article.title %></h1>

<div class="row justify-content-center mx-2">
<div class="my-2 mx-2">
    <div class="card bg-transparent border-0 text-center">
      <div class="card-body">
        <h5 class="card-text text-start lead"><%= simple_format(@article.description) %></h5>
        <%= link_to 'Back', articles_path(), class: "btn btn-transparent text-secondary border-secondary shadow" %>
        <% if logged_in? && (current_user.admin?) %>
          <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-transparent text-primary border-primary shadow" %>
          <%= link_to 'Delete', article_path(@article), data: { "turbo-method": :delete, "turbo-confirm": 'Are you sure?' }, class: "btn btn-transparent text-danger border-danger shadow" %>
        <% end %>
      </div>
      <div class="card-footer border-0 bg-transparent text-muted">
        <small>Created: <%= time_ago_in_words(@article.created_at) %> ago &ensp;|&ensp; Edited: <%= time_ago_in_words(@article.updated_at) %> ago</small>
      </div>
    </div>
</div>
</div>

app/views/layouts/_navigation.html.erb
  <!-- navbar items -->
  <nav class="navbar navbar-expand-lg p-4">
    <div class="container-fluid">
      <%= link_to 'emilysbookrants', root_path, class: "navbar-brand fs-2 link-animation-1" %>
      <button class="navbar-toggler border-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <svg xmlns="https://www.w3.org/2000/svg" width="24" height="24" style="fill: white; transform: ;msFilter:;">
          <path d="M4 6h16v2H4zm0 5h16v2H4zm0 5h16v2H4z"></path>
        </svg>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav fs-3 ms-auto">
          <li class="nav-item">
            <%= link_to 'blog', articles_path, class: "nav-link link-animation-2" %>
          </li>
          <li class="nav-item">
            <%= link_to 'book recs', root_path, class: "nav-link link-animation-2" %>
          </li>
          <li class="nav-item">
            <%= link_to 'about', about_path, class: "nav-link link-animation-2" %>
          </li>
          <li class="nav-item">
            <%= link_to 'chat', root_path, class: "nav-link disabled link-animation-2" %>
          </li>
          <% if logged_in? %>
            <div class="btn-group mx-3">
              <% if current_user.admin? %>
                <%= link_to "#{current_user.username} [admin]", user_path(current_user), type: "button", class: "nav-link link-animation-2" %>
                &nbsp;&nbsp;
                <%= gravatar_for current_user, size: 60, class: "d-inline" %>
              <% else %>
                <%= link_to current_user.username, user_path(current_user), type: "button", class: "nav-link link-animation-2" %>
                <%= gravatar_for current_user, size: 60, class: "d-inline" %>
              <% end %>
              </div>
              <btn type="button" class="btn btn-transparent nav-link border-0 text-white dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="visually-hidden">Toggle Dropdown</span>
              </btn>
              <ul class="dropdown-menu dropdown-menu-end">
                <li>
                  <%= link_to 'View Profile', user_path(current_user), class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to 'Edit Profile', edit_user_path(current_user), class: "dropdown-item" %>
                </li>
                <li><hr class="dropdown-divider"></li>
                <% if current_user.admin? %>
                  <%= link_to 'New Blog Post', new_article_path(), class: "dropdown-item" %>
                <% else %>
                  <li>
                    <%= link_to 'Delete Account', user_path(current_user), data: { "turbo-method": :delete, "turbo-confirm": 'Are you sure, this action cannot be undone?' }, class: "dropdown-item dropdown-danger" %>
                  </li>
                <% end %>
                <li><hr class="dropdown-divider"></li>                  
                <li>
                  <%= link_to 'Logout', logout_path(), data: { "turbo-method": :delete }, class: "dropdown-item" %>
                </li>
              </ul>
            </div> 
          <% else %>
            <li class="nav-item">
              <%= link_to 'Log in', login_path(), class: "nav-link link-animation-2" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_path(), class: "nav-link link-animation-2" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Emily's Book Rants</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="description" content="Emily's Blog on Books, Travel and Podcasts">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cookie&family=Ubuntu:wght@300;400;700&display=swap" rel="stylesheet">
  <%= favicon_link_tag asset_path('favicon-32x32.png') %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body>
  <div id="content">
    <%= render 'layouts/navigation' %>
  <%= yield %>
  </div>
  <%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/about.html.erb
<h1>ABOUT PAGE</h1>

app/views/pages/index.html.erb
  <!-- #TODO: Use book quotes api to rotate through random quotes -->
  <div class="container quotes-css">
    <p class="text-center mt-3 mb-3"><i>“You see, one of the best things about reading is that you'll always have something to think about when you're not reading.” - James Patterson</i></p>
    <p class="text-center mt-3 mb-3"><i>“Books are a uniquely portable magic.” - Stephen King</i></p>
    <p class="text-center mt-3 mb-3"><i>“Until I feared I would lose it, I never loved to read. One does not love breathing.” - Harper Lee, To Kill a Mockingbird</i></p>
  </div>

  <!-- Contains the 3 most recent posts  -->
  <div class="container">
    <div class="row recent-posts m-4">
    <% 
    i = 0
    Article.all.reverse.each do |article| 
      i += 1
      if i > 3
        break
      else
    %>
      <div class="col-md-8 offset-md-2 col-lg-4 offset-lg-0">
        <div class="card mx-md-4 my-2">
          <% if article.id.odd? %>
            <img src="https://images.unsplash.com/photo-1471440671318-55bdbb772f93?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2080&q=80" class="card-img-top homepage-blog-img" alt=<%= article.title %>>
          <% else %>
            <img src="https://images.unsplash.com/photo-1574629174070-63e3564b1916?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=849&q=80" class="card-img-top homepage-blog-img" alt=<%= article.title %>>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= article.title %></h5>
            <p class="card-text lead"><%= article.short_description %></p>
            <%= link_to 'Read More', article_path(article), class: "read-more" %>
          </div>
        </div>
      </div>
    <% end end %>
    </div>
  </div>

  <!-- Contains the on page nav links -->
  <div class="container">
    <div class="row m-4">
      <div class="col-md-8 offset-md-2 col-lg-4 offset-lg-0">
        <div class="card mx-md-4 my-2 bg-dark">
          <img src="https://images.unsplash.com/photo-1453928582365-b6ad33cbcf64?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1173&q=80" class="card-img" alt="Blog with Mac and Coffee">
          <div class="card-img-css"></div>
          <div class="card-img-overlay">
            <h1 class="card-title page-nav">
              <%= link_to 'Blog', root_path, class: "text-decoration-none link-animation-2" %>
            </h1>
          </div>
        </div>
      </div>
      <div class="col-md-8 offset-md-2 col-lg-4 offset-lg-0">
        <div class="card mx-md-4 my-2 bg-dark">
          <img src="https://images.unsplash.com/photo-1495446815901-a7297e633e8d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" class="card-img" alt="...">
          <div class="card-img-css"></div>
          <div class="card-img-overlay">
            <h1 class="card-title page-nav">
              <%= link_to 'Book Recs', root_path, class: "text-decoration-none link-animation-2" %>
            </h1>
          </div>
        </div>
      </div>
      <div class="col-md-8 offset-md-2 col-lg-4 offset-lg-0">
        <div class="card mx-md-4 my-2 bg-dark">
          <img src="https://images.unsplash.com/photo-1629131530695-30684ecb2366?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" class="card-img" alt="...">
          <div class="card-img-css"></div>
          <div class="card-img-overlay">
            <h1 class="card-title page-nav">
              <!-- #TODO: Remember to enable when chat section is done -->
              <%= link_to 'Connect', root_path, class: "text-decoration-none link-animation-2" %>
            </h1>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- About me card tag  -->
  <div class="card about-snip mb-3 w-lg-100">
    <div class="row g-0">
      <div class="col-xl-5 col-xxl-6">
        <%= image_tag "cover.jpg", class: "img-fluid abt-photo rounded-start", alt: "Emily" %>
      </div>
      <div class="col-xl-7 col-xxl-6">
        <div class="card-body">
          <h5 class="card-title">About Me</h5>
          <p class="card-text">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos pariatur architecto consequatur incidunt error, sunt sed ipsum rerum sapiente esse praesentium expedita veniam maiores quo quidem, provident repellat aspernatur ad.
          </p>
          <%= link_to 'Read More', about_path, class: "btn btn-secondary" %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container-xxl">
    <div class="alert alert-danger alert-dismissible fade show shadow" role="alert">
      <h3><strong>The following errors prevented the article from being saved</strong></h3>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_with(model: @user, data: { turbo: false }, local: true) do |f| %>
  <div class="container bg-secondary p-3 rounded shadow w-50">
    <div class="mb-3 row">
      <%= f.label :username, class: "col-sm-1 col-form-label text-light", for:"FormControlInput1" %>
      <div class="col-sm-11">
        <%= f.text_field :username, type: "text", class: "form-control shadow", id: "FormControlInput1", placeholder: "Enter a username" %>
      </div>
    </div>
    <div class="mb-3 row">
      <%= f.label :email, class: "col-sm-1 col-form-label text-light", for: "FormControlTextarea1" %>
      <div class="col-sm-11">
        <%= f.email_field :email, class: "form-control shadow", id: "FormControlTextarea1", placeholder: "Enter your email address" %>
      </div>
    </div>
    <div class="mb-3 row">
      <%= f.label :password, class: "col-sm-1 col-form-label text-light", for: "FormControlTextarea1" %>
      <div class="col-sm-11">
        <%= f.password_field :password, class: "form-control shadow", id: "FormControlTextarea1", placeholder: "Choose a password" %>
      </div>
    </div>
    <div class="form-group mb-3 row">
      <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class:"btn btn-large btn-outline-dark text-dark shadow col-4 fs-4 offset-4", id: "submit-button") %>
    </div>
  </div>
<% end %>
<div class="text-center my-3">
  <%= link_to '[ Cancel and return to homepage ]', root_path, class: "text-decoration-none", id: "return-to-listings" %>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<%= will_paginate @articles, class: "apple_pagination" %>

<div class="row justify-content-center mx-2 mb-3">
  <%= link_to 'Signup', new_user_path, class: "btn btn-light border-secondary shadow-3 w-75 py-3 my-4" %>
  <% @users.each do |user| %>
    <div class="col-lg-5 my-2 mx-2">
      <div class="card text-center shadow">
        <div class="card-header">
          <%= link_to user.username, user, class: "text-decoration-none text-dark fs-1 fw-bold text-capitalize" %>
        </div>
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to gravatar_for(user, size: 150), user %></h5>
          <%= link_to 'View profile', user, class: "btn btn-light text-success border-success shadow" %>
          <% if logged_in? %>
            <% if user == current_user %>
              <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-light text-primary border-primary shadow" %>
            <% end %>
            <% if current_user.admin? && !user.admin? %>
              <%= link_to 'Edit user', edit_user_path(user), class: "btn btn-light text-primary border-primary shadow" %>
              <%= link_to 'Delete Account', user_path(user), data: { "turbo-method": :delete, "turbo-confirm": "Are you sure you want to delete #{user.username}, this action cannot be undone?" }, class: "btn btn-light text-danger border-danger shadow" %>
            <% end %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small class="fst-italic">Profile created: <%= time_ago_in_words(user.created_at) %> ago</small>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= will_paginate @articles, class: "apple_pagination" %>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Signup for Emilysbookrants</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<%= gravatar_for @user, size: 200 %>
<h1 class="text-center mt-4"><%= @user.username %></h1>

<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to 'Edit profile', edit_user_path(@user), class: "btn btn-light text-primary border-primary shadow" %>
  </div>
<% end %>